### ISSUE TITLE
配置https域名后登录页面无法显示二维码，提示参数错误

### ISSUE THREAD

**Issue by anodaniel** [lianluoyi/easyink_Dashboard#15]
### 版本
1a38b70
### 项目环境信息
```
node v14.18.1 npm 6.14.15
```

### 是否必现
是

### 重现步骤
1. 用系统管理员账户登录，进入【系统管理】-【企微配置】，完成企业微信配置，并验证能够正确同步员工信息。
2. 进入【系统管理】-【企微配置】完成Sidebar服务域名配置，配置地址为<font color=red>https</font>协议，且<font color=red>不带端口号</font>。形式为：https://xxx.xxx.xxx 。域名配置无误，且在企业微信侧边栏验证能够正常访问企业话术库。
3. 退出管理员账户后，登录界面界面未能正确显示登录二维码，提示「参数错误」。界面显示如下：
<div data-v-0df23dc7="" class="qrcode-area">
	<div data-v-0df23dc7="" id="qrcode" class="qrcode">
		<iframe src="https://open.work.weixin.qq.com/wwopen/sso/qrConnect?login_type=jssdk&amp;
                     appid=[正确的APPID]&amp;
                     agentid=[正确的AGENTID]&amp;
                     redirect_uri=https:&amp;
                     state=0&amp;
                     href=https://wechattest-1253559996.cos.ap-guangzhou.myqcloud.com/qrcode.css&amp;lang=zh&amp;version=1.2.4" 
                frameborder="0" 
                scrolling="no" 
                width="300px" 
                height="400px">
        </iframe>
	</div>
</div>

### 期望的结果
能够支持不带端口的https域名

### 实际的结果
当前版本在配置不带端口的https域名后，登录时未能正确拼接二维码地址，导致二维码无法显示

---
打开登录页面，能够看到请求二维码URL地址拼接错误，其中redirect_uri仅包含 https: 未能正确匹配后端配置的dashboard地址
```xml
<div data-v-0df23dc7="" class="qrcode-area">
	<div data-v-0df23dc7="" id="qrcode" class="qrcode">
		<iframe src="https://open.work.weixin.qq.com/wwopen/sso/qrConnect?login_type=jssdk&amp;
                     appid=[正确的APPID]&amp;
                     agentid=[正确的AGENTID]&amp;
                     redirect_uri=https:&amp;
                     state=0&amp;
                     href=https://wechattest-1253559996.cos.ap-guangzhou.myqcloud.com/qrcode.css&amp;lang=zh&amp;version=1.2.4" 
                frameborder="0" 
                scrolling="no" 
                width="300px" 
                height="400px">
        </iframe>
	</div>
</div>
```

**Comment by lianluoyi** [comment]
已更新修复，拉取最新代码后即可解决
